### ISSUE TITLE
Make default template configurable

### ISSUE THREAD

**Issue by tulir** [maubot/rss#14]

**Comment by anmsh** [comment]
First, thank you for the all the hard work. 

I would love for this to be implemented some day. I was searching for a similar issue before opening a new one. I have an example where this could be useful. 

![image](https://user-images.githubusercontent.com/1550696/147047061-8af31cf2-0e7d-482c-9a7c-4b398179ccc4.png)
The commit message could be clearer and prominent making it easier to spot it.

**Comment by tulir** [comment]
For GitHub notifications, you should just use a [GitHub bot](https://github.com/maubot/github)

**Comment by anmsh** [comment]
Thanks for the correction, I will add this obversation in github bot repo later.

**Comment by tulir** [comment]
That screenshot is also not of the maubot github plugin, it's [go-neb](https://github.com/matrix-org/go-neb) which is known to not have very pretty messages. The maubot github plugin already produces much nicer-looking messages

**Comment by anmsh** [comment]
Oh, there is no way to know from the matrix bots page. This app is linked here: https://matrix.org/bots/, which is how I ended up here (rss, instead of github, but still) :)

This output looks pretty! Night and day difference, really. We are not self-hosting yet, just using the public server at the moment.
