### ISSUE TITLE
Failed to load feed: RPiLocator In Stock Feed

### ISSUE THREAD

**Issue by donicrosby** [maubot/rss#40]
Trying to add subscriptions to know when Raspberry PIs come back into stock, however: 

`!rss subscribe https://rpilocator.com/feed/`

Returns:
`Failed to load feed: <unknown>:13:2: mismatched tag`

**Comment by tulir** [comment]
That website is broken, they do user agent filtering. The latest version uses a custom user agent (https://github.com/maubot/rss/commit/877dcffb9c695ad0320fc6f5079f626d8bae452b), but I can't guarantee it'll work perfectly either since fundamentally broken websites just can't be fixed from the client side.
